#!/usr/bin/perl
# $Id$
#
# ShowUndocumented: Obtain a list of all undocumented ProFTPD configuration
#                   directives.
# Author: MacGyver aka Habeeb J. Dihu <macgyver@tos.net>
# Copyright(C) 1999, 2000, MacGyver.  All Rights Reserved.
#
# 06/Jan/02 - Hamster
#		Script modified to work with the sgml source and added into
#		the documentation cvs tree
#

use strict;

my %doc;
my $directive;
my @list;
##
## Environment
## PROFTPD -> $HOME/Proftpd/
## source for 1.2 lives in $PROFTPD/proftpd-1.2
## userguide lives in $PROFTPD/Userguide
##
chdir( "$ENV{PROFTPD}/Userguide/sgml" );

@list = <*>;
while( $directive = shift @list ) {
    chomp;
    if ( !/^CVS$/ ) {
       $doc{$directive} = 1;
    }
}
closedir( DOC );

chdir( "$ENV{PROFTPD}/proftpd-1.2/doc/" );
open(UNDOC,"./GetConf ../*/*.c|");

my $count = 0;
my $module = undef;
my $newmod = 0;

while(<UNDOC>) {
    chomp;

    s/^\s+//;
    s/\s+$//;
    s/^<//;
    s/^\///;
    s/>$//;
    
    next unless length($_) > 0;
    
    if(/^Module ([^\s]*):$/) {
	$module = $1;
	$newmod = 1;
	next;
    }
    
    if(!$doc{$_}) {
	if($newmod) {
	    print "\nModule: $module\n";
	    $newmod = 0;
	}
	
	print "  $_\n";
	$count++;
    }
}

if($count == 0) {
    print "No undocumented directives found.\n";
}
